[package]
name = "secretfinder"
version = "0.1.0"
edition = "2021"
authors= ["Mbithi"]
repository = "https://github.com/rotleaf/secretfinder"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
regex = "1.10.5"
reqwest = "0.12.5"
tokio = { version = "1.38.0", features = ["full"] }
